language: node_js
node_js:
  - '0.10'
  - '0.11'

deploy:
  provider: npm
  email: me@traviswebb.com
  api_key:
    secure: GFqlwAEvvw/tmlH0kK5LekYuI1RtCc92RArr4IQ5cSK8av9VQExDtOCq3YpU5p6eTiZRTkgv58MXWQmf7/nCi0NPbJyyiCvr0ewmOKlYdWlyyvyU0LTkxjixjEsksXyaN9KaLXe+Zg+QzsHn0lVGFkDAv2xcTd/1vT8/sqZHoK8=
  on:
    tags: true
    repo: tjwebb/pg-json-data-export
    all_branches: true
